In [19]:
from Bio.PDB.MMCIF2Dict import MMCIF2Dict

In [5]:
mmcif_dict = MMCIF2Dict('HIVI-RT/clean_bank/3di6.cif')

In [6]:
mmcif_dict['_pdbx_struct_assembly_gen.assembly_id']

['1', '2']

In [7]:
mmcif_dict['_pdbx_struct_assembly_gen.oper_expression']

['1,2', '1']

In [15]:
mmcif_dict['_pdbx_struct_assembly_gen.asym_id_list']

['A,B,C,D,E', 'A,B,C,D,E']

In [14]:
import numpy as np
#assembly_id = mmcif_dict['_pdbx_struct_assembly_gen.assembly_id']
assembly_id = '1'
assembly_id_list = np.array(assembly_id).tolist()
print(len(assembly_id_list))

1


In [18]:
asym_id = np.array(mmcif_dict['_pdbx_struct_assembly_gen.asym_id_list']).tolist()
for i in np.arange(len(asym_id)):
    print(asym_id[i])

A,B,C,D,E
A,B,C,D,E


In [19]:
id_remove = []
print(len(id_remove))

0


In [4]:
import numpy as np
arr1 = np.zeros(100)
arr2 = np.ones((10,10))
dictionary = {}
dictionary['arr1'] = arr1
dictionary['arr2'] = arr2
import pickle
with open('test.p', 'wb') as fp:
    pickle.dump(dictionary, fp)

In [6]:
!ls *.p

test.p


In [7]:
with open('test.p', 'rb') as fp:
    data = pickle.load(fp)
data

{'arr1': array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 'arr2': array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]

In [11]:
data['newfield'] = 2*np.ones(100)

In [12]:
with open('test.p', 'wb') as fp:
    pickle.dump(data, fp)

In [13]:
with open('test.p', 'rb') as fp:
    data = pickle.load(fp)
data

{'arr1': array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 'arr2': array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]

In [14]:
data['newfield']

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [17]:
data['newfield'] = 12*np.ones(50)

In [18]:
data['newfield']

array([ 12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,
        12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,
        12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,
        12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,
        12.,  12.,  12.,  12.,  12.,  12.])

In [1]:
listest = ['1']
print(len(listest))

1


In [1]:
import numpy as np

In [31]:
asym_id = np.array(('A','A','A','X','B','B','C','D','D','E'))
atom_id = np.array(('CA','C','O','CA','CA','N','CA','CA','CA','CA'))
print(asym_id)
print(atom_id)
mask = np.full(atom_id.shape[0],False)
print(mask)
mask_chain = np.copy(mask)
for chain in ('A','B'):
    print(chain)
    mask_chain += np.ma.masked_where(asym_id==chain, asym_id).mask
    print(mask_chain)
mask_atom = np.copy(mask)
for atom in ('CA',):
    print(atom)
    mask_atom += np.ma.masked_where(atom_id==atom, atom_id).mask
print(mask_atom)
mask = mask_chain*mask_atom
mask

['A' 'A' 'A' 'X' 'B' 'B' 'C' 'D' 'D' 'E']
['CA' 'C' 'O' 'CA' 'CA' 'N' 'CA' 'CA' 'CA' 'CA']
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
A
[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.]
B
[ 1.  1.  1.  0.  1.  1.  0.  0.  0.  0.]
CA
[ 1.  0.  0.  1.  1.  0.  1.  1.  1.  1.]


array([ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [32]:
mask = np.invert(mask.astype(bool))
mask

array([False,  True,  True,  True, False,  True,  True,  True,  True,  True], dtype=bool)